import { spawn } from "node:child_process";

// Generated by Window C migration: stdio bridge to the rust-analyzer language server.
// Behavior: spawn the server with stdio inheritance and proxy lifecycle signals.
// On ENOENT we emit a CrabCode-native install hint and exit 127 so callers can detect.

const PLUGIN_NAME = "rust-analyzer-lsp";
const SERVER_BINARY = "rust-analyzer";
const SERVER_ARGS: readonly string[] = [];
const INSTALL_HINT = "Install rust-analyzer. rustup (recommended): 'rustup component add rust-analyzer'. macOS: 'brew install rust-analyzer'. Ubuntu: 'sudo apt install rust-analyzer'. Arch: 'sudo pacman -S rust-analyzer'.";

function reportMissingBinary(binary: string, hint: string): void {
  process.stderr.write(
    `[${PLUGIN_NAME}] language server '${binary}' was not found on PATH.\n` +
      `Install hint: ${hint}\n`,
  );
}

function main(): void {
  const child = spawn(SERVER_BINARY, [...SERVER_ARGS], {
    stdio: ["inherit", "inherit", "inherit"],
    shell: false,
  });

  child.on("error", (err: NodeJS.ErrnoException) => {
    if (err.code === "ENOENT") {
      reportMissingBinary(SERVER_BINARY, INSTALL_HINT);
      process.exit(127);
      return;
    }
    process.stderr.write(`[${PLUGIN_NAME}] failed to start ${SERVER_BINARY}: ${err.message}\n`);
    process.exit(1);
  });

  child.on("exit", (code, signal) => {
    if (signal) {
      process.kill(process.pid, signal);
      return;
    }
    process.exit(code ?? 0);
  });

  const forward = (sig: NodeJS.Signals) => () => {
    if (!child.killed) child.kill(sig);
  };
  process.on("SIGINT", forward("SIGINT"));
  process.on("SIGTERM", forward("SIGTERM"));
  process.on("SIGHUP", forward("SIGHUP"));
}

main();
