import type { RecommendationRule } from "./rules.ts";
import { hasFramework, hasLanguage, hasSignal, makeRecommendation, signalEvidence } from "./rules.ts";

export const recommendationCatalog: RecommendationRule[] = [
  {
    id: "mcp-browser-automation",
    category: "mcp",
    title: "Browser automation MCP or plugin",
    priority: 91,
    when: (profile) => hasSignal(profile, "frontend") ? signalEvidence(profile, "frontend") : false,
    build: (_profile, evidence) => makeRecommendation({
      id: "mcp-browser-automation",
      category: "mcp",
      title: "Browser automation MCP or plugin",
      why: "This repository has frontend signals, so browser-driven verification can catch layout, routing, and interaction regressions.",
      install: "Resolve the browser automation integration from the configured CrabCode marketplace before enabling it.",
      priority: 91,
      evidence,
    }),
  },
  {
    id: "mcp-repository-hosting",
    category: "mcp",
    title: "Repository hosting MCP",
    priority: 74,
    when: (profile) => hasSignal(profile, "ci") ? signalEvidence(profile, "ci") : false,
    build: (_profile, evidence) => makeRecommendation({
      id: "mcp-repository-hosting",
      category: "mcp",
      title: "Repository hosting MCP",
      why: "CI configuration suggests pull request and workflow context would be useful when reviewing changes.",
      install: "Connect the repository MCP only if this workspace needs issue, pull request, or action visibility.",
      priority: 74,
      evidence,
    }),
  },
  {
    id: "skill-rust-verify",
    category: "skill",
    title: "Rust verification skill",
    priority: 90,
    when: (profile) => hasLanguage(profile, "Rust") ? signalEvidence(profile, "rust") : false,
    build: (_profile, evidence) => makeRecommendation({
      id: "skill-rust-verify",
      category: "skill",
      title: "Rust verification skill",
      why: "A dedicated skill can encode the project's preferred cargo check, clippy, format, and test sequence.",
      createAt: ".crabcode/skills/rust-verify/SKILL.md",
      priority: 90,
      evidence,
    }),
  },
  {
    id: "skill-frontend-review",
    category: "skill",
    title: "Frontend implementation review skill",
    priority: 86,
    when: (profile) => hasSignal(profile, "frontend") ? signalEvidence(profile, "frontend") : false,
    build: (_profile, evidence) => makeRecommendation({
      id: "skill-frontend-review",
      category: "skill",
      title: "Frontend implementation review skill",
      why: "Frontend work benefits from a repeatable review checklist for responsiveness, accessibility, state, and visual polish.",
      createAt: ".crabcode/skills/frontend-review/SKILL.md",
      priority: 86,
      evidence,
    }),
  },
  {
    id: "hook-typescript-typecheck",
    category: "hook",
    title: "Post-edit TypeScript check",
    priority: 93,
    when: (profile) => hasLanguage(profile, "TypeScript") ? signalEvidence(profile, "typescript") : false,
    build: (profile, evidence) => makeRecommendation({
      id: "hook-typescript-typecheck",
      category: "hook",
      title: "Post-edit TypeScript check",
      why: "TypeScript projects get fast feedback when edits trigger the existing typecheck or build command.",
      configPath: ".crabcode/settings.json",
      priority: 93,
      evidence: [...evidence, ...profile.buildCommands.filter((command) => command.toLowerCase().includes("typecheck")).slice(0, 2)],
      caveats: ["Keep this hook scoped to relevant source edits so it stays quick."],
    }),
  },
  {
    id: "hook-sensitive-file-guard",
    category: "hook",
    title: "Sensitive-file edit guard",
    priority: 89,
    when: (profile) => hasSignal(profile, "secret-sensitive-config") ? signalEvidence(profile, "secret-sensitive-config") : false,
    build: (_profile, evidence) => makeRecommendation({
      id: "hook-sensitive-file-guard",
      category: "hook",
      title: "Sensitive-file edit guard",
      why: "Secret-adjacent configuration exists, so edits to environment files should require extra confirmation.",
      configPath: ".crabcode/settings.json",
      priority: 89,
      evidence,
    }),
  },
  {
    id: "hook-rust-verify",
    category: "hook",
    title: "Rust check hook",
    priority: 82,
    when: (profile) => hasLanguage(profile, "Rust") ? signalEvidence(profile, "rust") : false,
    build: (_profile, evidence) => makeRecommendation({
      id: "hook-rust-verify",
      category: "hook",
      title: "Rust check hook",
      why: "Cargo check or clippy after Rust source edits catches errors before deeper review.",
      configPath: ".crabcode/settings.json",
      priority: 82,
      evidence,
      caveats: ["Prefer a fast check command for routine edits and leave full tests to deliberate verification."],
    }),
  },
  {
    id: "agent-repository-explorer",
    category: "agent",
    title: "Repository explorer agent",
    priority: 78,
    when: (profile) => hasSignal(profile, "monorepo") || hasSignal(profile, "rust-workspace") ? [...signalEvidence(profile, "monorepo"), ...signalEvidence(profile, "rust-workspace")] : false,
    build: (_profile, evidence) => makeRecommendation({
      id: "agent-repository-explorer",
      category: "agent",
      title: "Repository explorer agent",
      why: "The project has workspace signals, so a dedicated explorer can map ownership, entrypoints, and verification paths quickly.",
      createAt: ".crabcode/agents/repository-explorer.md",
      priority: 78,
      evidence,
    }),
  },
  {
    id: "agent-security-reviewer",
    category: "agent",
    title: "Security reviewer agent",
    priority: 88,
    when: (profile) => hasSignal(profile, "security-sensitive") ? signalEvidence(profile, "security-sensitive") : false,
    build: (_profile, evidence) => makeRecommendation({
      id: "agent-security-reviewer",
      category: "agent",
      title: "Security reviewer agent",
      why: "Security-sensitive paths deserve a focused review pass for auth flow, secret handling, validation, and payment logic.",
      createAt: ".crabcode/agents/security-reviewer.md",
      priority: 88,
      evidence,
    }),
  },
  {
    id: "plugin-frontend-workflow",
    category: "plugin",
    title: "Frontend workflow plugin",
    priority: 77,
    when: (profile) => hasSignal(profile, "frontend") && (hasFramework(profile, "React") || hasFramework(profile, "Vue") || hasFramework(profile, "Next.js")) ? signalEvidence(profile, "frontend") : false,
    build: (_profile, evidence) => makeRecommendation({
      id: "plugin-frontend-workflow",
      category: "plugin",
      title: "Frontend workflow plugin",
      why: "A bundled frontend workflow can combine design review, browser verification, and component-focused checks.",
      install: "Use the configured CrabCode marketplace to select an available frontend workflow plugin.",
      priority: 77,
      evidence,
      caveats: ["Do not hardcode a marketplace package name until availability is confirmed."],
    }),
  },
  {
    id: "plugin-test-workflow",
    category: "plugin",
    title: "Test automation workflow plugin",
    priority: 72,
    when: (profile) => profile.testCommands.length > 0 || hasSignal(profile, "js-test-tooling") ? [...profile.testCommands, ...signalEvidence(profile, "js-test-tooling")] : false,
    build: (_profile, evidence) => makeRecommendation({
      id: "plugin-test-workflow",
      category: "plugin",
      title: "Test automation workflow plugin",
      why: "The project already has test tooling, so a plugin can standardize targeted test selection and failure triage.",
      install: "Choose an available CrabCode testing workflow plugin only after checking the marketplace catalog.",
      priority: 72,
      evidence,
    }),
  },
  {
    id: "workflow-init-context",
    category: "workflow",
    title: "Initialize CrabCode project context",
    priority: 84,
    when: (profile) => hasSignal(profile, "missing-crabcode-context") ? signalEvidence(profile, "missing-crabcode-context") : false,
    build: (_profile, evidence) => makeRecommendation({
      id: "workflow-init-context",
      category: "workflow",
      title: "Initialize CrabCode project context",
      why: "A concise CRABCODE.md gives future sessions stable project commands, conventions, and safety notes.",
      createAt: "CRABCODE.md",
      priority: 84,
      evidence,
    }),
  },
  {
    id: "workflow-refine-existing-skills",
    category: "workflow",
    title: "Refine existing CrabCode skills",
    priority: 80,
    when: (profile) => hasSignal(profile, "crabcode-config") ? signalEvidence(profile, "crabcode-config").filter((item) => item.includes(".crabcode/skills")) : false,
    build: (_profile, evidence) => makeRecommendation({
      id: "workflow-refine-existing-skills",
      category: "workflow",
      title: "Refine existing CrabCode skills",
      why: "Existing skills should be reviewed before creating duplicates; tighten descriptions, examples, and verification commands first.",
      priority: 80,
      evidence,
    }),
  },
];

