#!/usr/bin/env python3
"""Build the CN marketplace ZIP from immutable Git objects.

The archive is generated by ``git archive`` from an exact commit, so checkout
mtimes and uncommitted files cannot affect its bytes. The optional existing
archive comparison is the fail-closed guard for a content-addressed public
object: the same commit SHA may never name different bytes.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
from pathlib import Path, PurePosixPath
import subprocess
import sys
import tempfile


MANIFEST_PATH = ".crabcode-plugin/mirror-distribution.json"


def git(repo: Path, *args: str, text: bool = False) -> bytes | str:
    environment = {**os.environ, "TZ": "UTC"}
    completed = subprocess.run(
        ["git", "-C", str(repo), *args],
        check=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=text,
        env=environment,
    )
    return completed.stdout


def canonical_prefix(raw: str) -> str:
    if not raw or raw.startswith("/") or "\\" in raw:
        raise ValueError("archive prefix must be a non-empty relative POSIX path")
    parts = PurePosixPath(raw).parts
    if any(part in ("", ".", "..") for part in parts):
        raise ValueError("archive prefix must not contain empty, dot, or parent segments")
    return raw.rstrip("/") + "/"


def exclusions(repo: Path, sha: str) -> list[str]:
    try:
        raw = git(repo, "show", f"{sha}:{MANIFEST_PATH}")
    except subprocess.CalledProcessError:
        return []
    try:
        data = json.loads(raw)
    except (TypeError, json.JSONDecodeError) as error:
        raise ValueError(f"invalid {MANIFEST_PATH}: {error}") from error
    prefixes = data.get("excludePrefixes", [])
    if not isinstance(prefixes, list) or not all(isinstance(item, str) for item in prefixes):
        raise ValueError("mirror-distribution excludePrefixes must be a string array")
    for item in prefixes:
        if "/tests/" not in item:
            raise ValueError(f"exclude prefix must remain under /tests/: {item}")
        parts = item.split("/")
        if not item or item.startswith("/") or "\\" in item or ".." in parts:
            raise ValueError(f"exclude prefix must be a repository-relative POSIX path: {item}")
    return sorted(set(prefixes))


def reject_unsupported_tree_entries(repo: Path, sha: str) -> None:
    raw = git(repo, "ls-tree", "-r", "-z", sha)
    assert isinstance(raw, bytes)
    for record in raw.split(b"\0"):
        if not record:
            continue
        metadata, raw_path = record.split(b"\t", 1)
        mode = metadata.split(b" ", 1)[0]
        try:
            path = raw_path.decode("utf-8")
        except UnicodeDecodeError as error:
            raise ValueError("release tree contains a non-UTF-8 path") from error
        pure = PurePosixPath(path)
        if path.startswith("/") or "\\" in path or ".." in pure.parts:
            raise ValueError(f"release tree contains an unsafe archive path: {path}")
        if mode in (b"120000", b"160000"):
            kind = "symlink" if mode == b"120000" else "submodule"
            raise ValueError(f"release tree contains unsupported {kind}: {path}")


def reject_archive_attribute_transforms(repo: Path, sha: str) -> None:
    raw = git(repo, "ls-tree", "-r", "--name-only", "-z", sha)
    assert isinstance(raw, bytes)
    attribute_paths = [
        value.decode("utf-8")
        for value in raw.split(b"\0")
        if value and PurePosixPath(value.decode("utf-8")).name == ".gitattributes"
    ]
    for attribute_path in attribute_paths:
        content = git(repo, "show", f"{sha}:{attribute_path}", text=True)
        assert isinstance(content, str)
        for line_number, line in enumerate(content.splitlines(), start=1):
            stripped = line.strip()
            if not stripped or stripped.startswith("#"):
                continue
            fields = stripped.split()
            if any(
                field in ("export-ignore", "export-subst")
                or field.startswith("export-ignore=")
                or field.startswith("export-subst=")
                for field in fields[1:]
            ):
                raise ValueError(
                    "release archives forbid export-ignore/export-subst transforms: "
                    f"{attribute_path}:{line_number}"
                )


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as source:
        for chunk in iter(lambda: source.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def build(
    repo: Path,
    output: Path,
    commit: str,
    prefix: str,
    existing_archive: Path | None,
) -> tuple[str, str, list[str]]:
    repo = repo.resolve(strict=True)
    output = output.resolve()
    output.parent.mkdir(parents=True, exist_ok=True)
    resolved = git(repo, "rev-parse", "--verify", f"{commit}^{{commit}}", text=True)
    assert isinstance(resolved, str)
    sha = resolved.strip()
    if len(sha) != 40 or any(character not in "0123456789abcdef" for character in sha):
        raise ValueError(f"resolved commit is not a lowercase full SHA: {sha!r}")

    archive_prefix = canonical_prefix(prefix)
    excluded = exclusions(repo, sha)
    reject_unsupported_tree_entries(repo, sha)
    reject_archive_attribute_transforms(repo, sha)

    descriptor, temporary_name = tempfile.mkstemp(
        prefix=f".{output.name}.", suffix=".tmp", dir=output.parent
    )
    os.close(descriptor)
    temporary = Path(temporary_name)
    try:
        pathspecs = [".", *(f":(exclude,glob){item}**" for item in excluded)]
        subprocess.run(
            [
                "git",
                "-C",
                str(repo),
                "archive",
                "-9",
                "--format=zip",
                f"--prefix={archive_prefix}",
                f"--output={temporary}",
                sha,
                "--",
                *pathspecs,
            ],
            check=True,
            env={**os.environ, "TZ": "UTC"},
        )
        built_digest = sha256(temporary)
        if existing_archive is not None:
            existing_archive = existing_archive.resolve(strict=True)
            existing_digest = sha256(existing_archive)
            if existing_digest != built_digest or not _same_bytes(temporary, existing_archive):
                raise ValueError(
                    "refusing to overwrite an existing same-SHA archive with different bytes: "
                    f"built={built_digest} existing={existing_digest}"
                )
        os.replace(temporary, output)
    finally:
        temporary.unlink(missing_ok=True)

    return sha, sha256(output), excluded


def _same_bytes(left: Path, right: Path) -> bool:
    if left.stat().st_size != right.stat().st_size:
        return False
    with left.open("rb") as left_file, right.open("rb") as right_file:
        while True:
            left_chunk = left_file.read(1024 * 1024)
            right_chunk = right_file.read(1024 * 1024)
            if left_chunk != right_chunk:
                return False
            if not left_chunk:
                return True


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--repo", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--commit", default="HEAD")
    parser.add_argument(
        "--prefix", default="marketplaces/crabcode-plugins-official/"
    )
    parser.add_argument("--existing-archive", type=Path)
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    try:
        sha, digest, excluded = build(
            args.repo,
            args.output,
            args.commit,
            args.prefix,
            args.existing_archive,
        )
    except (OSError, subprocess.CalledProcessError, ValueError) as error:
        print(f"ERROR: {error}", file=sys.stderr)
        return 1
    print(
        json.dumps(
            {"sha": sha, "sha256": digest, "excludedPrefixes": excluded},
            ensure_ascii=False,
            sort_keys=True,
        )
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
